name: "$(Build.SourceBranchName)-init"

pr:
  branches:
    include:
      - "main"
  paths:
    include:
      - src/*

trigger:
  branches:
    include:
      - "main"
  paths:
    include:
      - src/*

# Configure parameters for running the build
parameters:
  - name: deploy
    displayName: Deploy Environment
    type: boolean
    default: true
  - name: destroy
    displayName: Destroy Environment
    type: boolean
    default: false
  - name: upload
    displayName: Upload generated files
    type: boolean
    default: false
  - name: force_deploy
    displayName: Force deploy regardless of branch
    type: boolean
    default: false
  - name: pre_release
    displayName: Create a pre-release from feature branch
    type: boolean
    default: false

  - name: stages
    type: object
    default:
      - stage: NonProd
        dependsOn: Build
        condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
        environment_shortname: nonprod
        deployment_infra: InfraNonProd
        deployment_apps: ACANonProd
      - stage: Prod
        dependsOn: Build
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
        environment_shortname: prod
        deployment_infra: InfraProd
        deployment_apps: ACAProd

  - name: debug
    displayName: Turn on debug for the Independent Runner
    type: boolean
    default: false

variables:
  - template: ../build/azDevOps/azure/pipeline-vars.yml  
  - template: aca-vars.yml
  - name: appname
    value: "frontendapp"
  - name: docker_build_args
    value: "src/app"
  - name: container_app_name
    value: "frontendapplication"
  - name: tf_state_key
    value: $(domain)_$(appname)

  - name: CHEF_LICENSE
    value: accept-silent
  # Versioning
  - name: version_major
    value: 0
  - name: version_minor
    value: 1
  - name: version_revision
    value: $[counter(join(variables['version_major'], join('-', variables['version_minor'])), 0)]
  - name: version_number
    value: "$(version_major).$(version_minor).$(version_revision)-${{ lower(variables['Build.SourceBranchName']) }}"

stages:
  - stage: Build
    variables:
      - group: ensono-sp-creds #stacks-credentials-nonprod-kv
    jobs:
      - job: Build
        pool:
          vmImage: $(pool_vm_image)
        steps:
          - template: ../build/azDevOps/templates/setup.yml
            parameters:
              TaskctlVersion: ${{ variables.TaskctlVersion }}

          - task: Bash@3
            displayName: "TaskCTL: Setup"
            inputs:
              targetType: inline
              script: taskctl setup
            env:
              DOCKER_IMAGE_TAG: $(version_number)

          - task: Bash@3
            displayName: "TaskCTL: Lint"
            inputs:
              targetType: inline
              script: taskctl lint
            env:
              TF_FILE_LOCATION: /app/src/terraform
              CLOUD_PLATFORM: "$(cloud_platform)"

          - task: Bash@3
            displayName: "TaskCTL: Build Image"
            inputs:
              targetType: inline
              script: |
                taskctl build:container
            env:
              CLOUD_PROVIDER: "$(cloud_platform)" #$(cloud_provider) # Azure
              ARM_TENANT_ID: $(azure-tenant-id)
              ARM_SUBSCRIPTION_ID: $(azure-subscription-id)
              ARM_CLIENT_ID: $(azure-client-id)
              ARM_CLIENT_SECRET: $(azure-client-secret)

              DOCKER_CONTAINER_REGISTRY_NAME: $(container_registry_server)
              REGISTRY_RESOURCE_GROUP: $(registry_resoruce_group)
              DOCKER_IMAGE_NAME: $(appname)
              DOCKER_BUILD_ARGS: $(docker_build_args)
              DOCKER_IMAGE_TAG: $(version_number)

  # Called Non-Prod instead of Dev as all Non-Production stages will deploy to here
  - ${{ each stage in parameters.stages }}:
      - stage: ${{ stage.stage }}
        dependsOn: ${{ stage.dependsOn }}
        condition: and(succeeded(), or(${{ stage.condition }}, ${{ parameters.force_deploy }}))
        variables:
          # Pull in the non-production credentials for the build to use
          - group: ensono-sp-creds #stacks-credentials-nonprod-kv #ensono-sp-creds
        jobs:
          - deployment: ${{ stage.deployment_apps }}
            environment: ${{ variables.domain }}-${{ stage.environment_shortname }}
            pool:
              vmImage: $(pool_vm_image)

            strategy:
              runOnce:
                deploy:
                  steps:
                    - template: ../build/azDevOps/templates/setup.yml
                      parameters:
                        TaskctlVersion: ${{ variables.TaskctlVersion }}


                    # Create a tfvars file for the values
                    # This is so that variables can be set and reused as required
                    - task: Bash@3
                      displayName: Create Terraform variables file
                      inputs:
                        targetType: inline
                        script: |
                          taskctl infra:vars
                      env:
                        TASKCTL_DEBUG: ${{ lower(parameters.debug) }}
                        TF_FILE_LOCATION: /app/src/terraform
                        CLOUD_PLATFORM: "$(cloud_platform)"
                        TF_BACKEND_INIT: "key=$(tf_state_key),storage_account_name=$(tf_state_storage),resource_group_name=$(tf_state_rg),container_name=$(tf_state_container)"

                        TF_VAR_name_company: $(company)
                        TF_VAR_name_project: $(project)
                        TF_VAR_name_component: $(domain)
                        TF_VAR_name_environment: ${{ stage.environment_shortname }}
                        TF_VAR_stage: ${{ stage.environment_shortname }}
                        TF_VAR_location: $(region)
                        TF_VAR_acr_name:  $(container_registry_name)
                        TF_VAR_acr_rg:  $(registry_resoruce_group)
                        TF_VAR_acae_name: $(container_environment_name)
                        TF_VAR_image_name: "$(container_registry_server)/$(appname)"
                        TF_VAR_image_tag: $(version_number)
                        TF_VAR_container_app_name: $(container_app_name)

                    # Upload the Terraform variables file and the plan for debugging
                    - ${{ if eq(parameters.upload, true) }}:
                        - template: ../build/azDevOps/templates/upload.yml
                          parameters:
                            contents: $(Build.SourcesDirectory)/src/terraform/*.tfvars

                    # Remove the container app if the parameter has been set
                    - ${{ if eq(parameters.destroy, true) }}:
                        - task: Bash@3
                          displayName: Destroy environment
                          inputs:
                            targetType: inline
                            script: |
                              taskctl infrastructure_destroy
                          env:
                            TF_FILE_LOCATION: /app/src/terraform
                            TF_BACKEND_INIT: "key=$(tf_state_key),container_name=$(tf_state_container),storage_account_name=$(tf_state_storage),resource_group_name=$(tf_state_rg)"
                            TF_BACKEND_DESTROY_PLAN: "-input=false,-out=\"destroy\""
                            TF_VAR_name_environment: ${{ stage.environment_shortname }}
                            CLOUD_PLATFORM: "$(cloud_platform)"

                    # Create the container app
                    - ${{ if eq(parameters.deploy, true) }}:
                        - task: Bash@3
                          displayName: "TaskCTL: infrastructure"
                          inputs:
                            targetType: inline
                            script: |
                              taskctl infrastructure
                          env:
                            TF_FILE_LOCATION: /app/src/terraform
                            TF_BACKEND_INIT: "key=$(tf_state_key),container_name=$(tf_state_container),storage_account_name=$(tf_state_storage),resource_group_name=$(tf_state_rg)"
                            TF_BACKEND_PLAN: "-input=false,-out=\"tfplan\""
                            TF_VAR_name_environment: ${{ stage.environment_shortname }}
                            CLOUD_PLATFORM: "$(cloud_platform)"

                    # Perform infrastructure tests
                    - ${{ if eq(parameters.deploy, true) }}:
                        - template: ../build/azDevOps/templates/infra-tests.yml
                          parameters:
                            CHEF_LICENSE: $(CHEF_LICENSE)
                            INSPEC_FILES: /app/src/tests
                            REPORT_FILENAME: inspec_azure_aca.xml
                            TF_FILE_LOCATION: /app/src/terraform
                            TF_VAR_name_environment: ${{ stage.environment_shortname }}
                            TF_VAR_location: $(region)

                    - ${{ if eq(parameters.deploy, true) }}:
                        - task: PublishTestResults@2
                          inputs:
                            testResultsFormat: JUnit
                            testResultsFiles: outputs/tests/inspec_azure_aca.xml
                            testRunTitle: Terraform ACA Tests
                            failTaskOnFailedTests: true

  - stage: Release
    dependsOn:
      - ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
          - NonProd
      - ${{ else }}:
          - Prod
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(${{ parameters.pre_release }}, true)))
    variables:
      # TODO: Credentials should come from another group. `amido-stacks-github-credentials` are the old creds
      - group: github-creds  #amido-stacks-webapp
      - name: version_number
        value: "$(version_major).$(version_minor).$(version_revision)"
    jobs:
      - job: CreateGitHubRelease
        pool:
          vmImage: $(pool_vm_image)
        steps:
          - template: ../build/azDevOps/templates/setup.yml
            parameters:
              TaskctlVersion: ${{ variables.TaskctlVersion }}

          - task: Bash@3
            displayName: Publish Release
            inputs:
              targetType: inline
              script: |
                taskctl release
            env:
              STAGE: "release"
              PUBLISH_RELEASE: "true"
              GITHUB_TOKEN: "$(API_KEY)"
              ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
                PRERELEASE: "true"
